# Generated by Django 5.0.2 on 2024-03-25 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_network_counselee_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counselee',
            name='network',
        ),
    ]
